<?php
/**
 * Message: 联系controller
 * User: jzc
 * Date: 2019/6/4
 * Time: 1:57 PM
 * Return:
 */

namespace frontend\controllers;


class ContactController extends CommonController
{
    public $layout = 'index';
    public function actions()
    {
        return parent::actions(); // TODO: Change the autogenerated stub
    }

    public function actionIndex()
    {
        return $this->render('index');
    }
}